### ISSUE TITLE
Script fails before it asks me for admin password

### ISSUE THREAD

**Issue by atlas1442** [brianddk/trezor-tails#1] opened 2019-08-28 13:49 UTC
rsync: mkdir "/live/persistence/TailsData_unlocked/dotfiles" failed: Permission denied (13)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
errexit on line 66 /dev/fd/63
 This is the final two lines when the program fails.  Any idea what the issue is?

**Comment by brianddk** [comment] 2020-04-26 20:04
Yep... it requires you set the Admin Password when you boot into tails.  It's on that welcome wizard where you unlock the persistent storage.  Look for the little "+" sign at the bottom of the dialog.

I've also updated the whole repo to work with Tails v4.5 and Trezor's April 2020 FW rollout.

**Comment by brianddk** [comment] 2020-04-29 15:47
I can't reproduce on Tails 3.14, but have moved to Tails 4.5 now.  If you could just ensure you enable the Admin account on start up and try again with [release v1.0](https://github.com/brianddk/trezor-tails/releases/tag/v1.0), I'm hoping that will clear things up.

I'll assume so, and close this for now, but please reopen if your errors persist.

**Closed as completed by brianddk** 2020-04-29 15:47 UTC

**Comment by aegyed91** [comment] 2020-05-31 17:47
@brianddk I am facing the same (or very similar) issue. It seems like, in the first stage, various modules generate config files and at the end (bootstrap.sh#L73) of `user_first_stage` it wants to copy all these config files at `/live/persistence/TailsData_unlocked/dotfiles`. As the `dotfiles` directory does not exist, it tries to create it. The problem is, `TailsData_unlocked` is owned by `root` and only `sudo_second_stage` has root privileges. 

I am running Tails 4.6 (it might work in 4.5, I am using an unsupported version).

The options I use:

```bash
# OPTIONS: Everything before /END can be modified to your preference.
# Add a `#` in column one to disable a feature
branch="master"
#branch="dev"
#branch="v0.12.0"
#branch="scratch"
[ -z "$available" ] && export available="
#05_swap
10_udev
15_bash
20_gnome
#25_python_trezor
30_bridge
#35_chromium
#37_brave_browser
#40_electrum_btc
#45_electron_bch
"
# /END
```

P.S: this thing is awesome, thanks a lot for making it open source!

**EDIT:** apparently I've failed to properly configure my persistent storage, had to enable the [Dotfiles feature](https://tails.boum.org/doc/first_steps/persistence/configure/index.en.html). Sorry, I am new to Tails.

**Comment by brianddk** [comment] 2020-06-01 07:33
> apparently I've failed to properly configure my persistent storage

@aegyed-91, no worries.  I'll add in the WIKI that I assume you enable ***ALL*** persistent storage features.
